language: go

go: 1.14.2

arch:
  - amd64
  - arm64

install:
  - go get -v .
  - go build .
  - pwd
  - ls -ltra *

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH
    file: prometheus-json-exporter
    overwrite: true
    on:
      tags: true
