language: go

go: 1.14.2

arch:
  - amd64
  - arm64

install:
  - go get -v .
  - go build .

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file: prometheus-json-exporter
  skip_cleanup: true
  on:
    tags: true
