language: go

go: 1.12

install:
  - go get -v .
  - go build .

deploy:
  provider: releases
  api_key:
    secure: 214e82a4e460ee29067e94bbf1d34829016e3aaa
  file: prometheus-json-exporter
  skip_cleanup: true
  on:
    tags: true
